import os
import hmac
import hashlib
import requests
from flask import Flask, request, jsonify
from dotenv import load_dotenv

load_dotenv()

app = Flask(__name__)

# Configuration
DEVIN_API_KEY = os.getenv("DEVIN_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
SUPERSET_REPO = os.getenv("SUPERSET_REPO", "maidang111/superset")
REMEDY_REPO = os.getenv("REMEDY_REPO", "maidang111/Remedy")
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET")

def verify_webhook_signature(payload, signature):
    """Verify GitHub webhook signature"""
    if not WEBHOOK_SECRET:
        return True  # Skip verification if no secret configured
    
    hash_algorithm, github_signature = signature.split('=', 1)
    if hash_algorithm != 'sha256':
        return False
    
    mac = hmac.new(WEBHOOK_SECRET.encode(), msg=payload, digestmod=hashlib.sha256)
    expected_signature = mac.hexdigest()
    
    return hmac.compare_digest(expected_signature, github_signature)

def extract_issue_context(webhook_data):
    """Extract relevant context from GitHub issue webhook"""
    issue = webhook_data.get('issue', {})
    repository = webhook_data.get('repository', {})
    
    context = {
        'issue_number': issue.get('number'),
        'issue_title': issue.get('title'),
        'issue_body': issue.get('body', ''),
        'issue_url': issue.get('html_url'),
        'repo_name': repository.get('full_name'),
        'repo_url': repository.get('html_url'),
        'labels': [label['name'] for label in issue.get('labels', [])],
        'state': issue.get('state'),
        'user': issue.get('user', {}).get('login')
    }
    return context

def create_devin_session(issue_context):
    """Create a Devin session to fix the issue"""
    print(f"Using API key: {DEVIN_API_KEY[:20]}...")
    prompt = f"""
    Fix the following issue from the Superset repository:
    
    Issue Title: {issue_context['issue_title']}
    Issue Body: {issue_context['issue_body']}
    Issue URL: {issue_context['issue_url']}
    
    Please analyze this issue and create a fix. The fix should be implemented in the Remedy repository.
    Return the complete code changes needed to address this issue.
    """
    
    headers = {
        "Authorization": f"Bearer {DEVIN_API_KEY}",
        "Content-Type": "application/json"
    }
    
    payload = {
        "prompt": prompt,
        "idempotent": True
    }
    
    response = requests.post(
        "https://api.devin.ai/v1/sessions",
        headers=headers,
        json=payload
    )
    
    print(f"Devin API response status: {response.status_code}")
    print(f"Devin API response: {response.text}")
    
    if response.status_code != 200:
        raise Exception(f"Devin API error: {response.status_code} - {response.text}")
    
    return response.json()

def monitor_devin_session(session_id):
    """Monitor Devin session until completion or timeout"""
    headers = {
        "Authorization": f"Bearer {DEVIN_API_KEY}"
    }
    
    import time
    max_attempts = 12  # 1 minute max for demo
    attempt = 0
    
    while attempt < max_attempts:
        response = requests.get(
            f"https://api.devin.ai/v1/sessions/{session_id}",
            headers=headers
        )
        
        if response.status_code != 200:
            raise Exception(f"Devin session check error: {response.status_code}")
        
        session_data = response.json()
        status = session_data.get('status_enum') or session_data.get('status')
        
        print(f"Session status: {status}")
        
        if status in ['finished', 'blocked', 'completed']:
            return session_data
        
        attempt += 1
        time.sleep(5)
    
    # For demo purposes, return session data even if still running
    print("Session still running after timeout, proceeding with session URL")
    return session_data

def create_github_pr(issue_context, session_data):
    """Create a PR in the Remedy repository"""
    # Extract the fix from the session
    # For now, we'll create a simple PR with the session URL
    session_url = session_data.get('url', '')
    
    pr_title = f"Fix: {issue_context['issue_title']}"
    pr_body = f"""
    Automated fix for issue #{issue_context['issue_number']} from {issue_context['repo_name']}
    
    Original Issue: {issue_context['issue_url']}
    
    This PR was generated by Devin AI. Session URL: {session_url}
    
    Issue Context:
    - Title: {issue_context['issue_title']}
    - Labels: {', '.join(issue_context['labels'])}
    """
    
    # First, create a new branch
    branch_name = f"fix/issue-{issue_context['issue_number']}"
    
    # Get default branch
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    repo_response = requests.get(
        f"https://api.github.com/repos/{REMEDY_REPO}",
        headers=headers
    )
    default_branch = repo_response.json().get('default_branch', 'main')
    
    # Create branch (simplified - assumes branch exists or we create it)
    # For a full implementation, we'd need to:
    # 1. Get the default branch SHA
    # 2. Create a new branch from that SHA
    # 3. Make commits to the branch
    # 4. Create the PR
    
    # For this demo, we'll create the PR directly (will fail if branch doesn't exist)
    pr_payload = {
        "title": pr_title,
        "body": pr_body,
        "head": branch_name,
        "base": default_branch
    }
    
    pr_response = requests.post(
        f"https://api.github.com/repos/{REMEDY_REPO}/pulls",
        headers=headers,
        json=pr_payload
    )
    
    if pr_response.status_code != 201:
        raise Exception(f"Failed to create PR: {pr_response.status_code} - {pr_response.text}")
    
    return pr_response.json()

@app.route('/webhook', methods=['POST'])
def webhook():
    """Handle GitHub webhook for issues"""
    # Verify signature
    signature = request.headers.get('X-Hub-Signature-256')
    if signature and not verify_webhook_signature(request.data, signature):
        return jsonify({"error": "Invalid signature"}), 401
    
    # Check if this is an issue event
    event_type = request.headers.get('X-GitHub-Event')
    if event_type != 'issues':
        return jsonify({"message": "Ignoring non-issue event"}), 200
    
    webhook_data = request.json
    
    # Only process newly opened issues
    action = webhook_data.get('action')
    if action != 'opened':
        return jsonify({"message": "Ignoring non-opened issue"}), 200
    
    # Extract issue context
    issue_context = extract_issue_context(webhook_data)
    print(f"Processing issue: {issue_context['issue_title']}")
    
    try:
        # Create Devin session
        session_data = create_devin_session(issue_context)
        session_id = session_data.get('session_id')
        print(f"Created Devin session: {session_id}")
        
        # Skip monitoring for demo - proceed directly to PR creation
        print("Skipping session monitoring for demo, proceeding to PR creation")
        
        # Create PR with session URL
        pr_data = create_github_pr(issue_context, session_data)
        print(f"Created PR: {pr_data.get('html_url')}")
        
        return jsonify({
            "message": "Issue processed successfully",
            "session_id": session_id,
            "session_url": session_data.get('url'),
            "pr_url": pr_data.get('html_url')
        }), 200
        
    except Exception as e:
        print(f"Error processing issue: {str(e)}")
        return jsonify({"error": str(e)}), 500

@app.route('/', methods=['GET'])
def index():
    """Root endpoint with basic info"""
    return jsonify({
        "service": "Remedy Webhook Server",
        "status": "running",
        "endpoints": {
            "webhook": "/webhook (POST)",
            "health": "/health (GET)"
        }
    }), 200

@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint"""
    return jsonify({"status": "healthy"}), 200

if __name__ == '__main__':
    port = int(os.getenv('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=True)
